require:
  - rubocop-rspec
  - rubocop/rspec/focused

inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true
  DisplayStyleGuide: true
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Metrics/LineLength:
  Max: 120

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

RSpec/FilePath:
  Exclude:
    - 'spec/routing/**/*'
