# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6d759452383880dcd1c89d2fd189e44da99618cb2e37460ccf77d1df19f308eb234a9994226b23b8f6deb50319fde323a7801f3ababac36fd967248b8e8c68c

test:
  secret_key_base: dbc32ee2b08f88a53502a0360278d2dbd9e2ce22c942a772bf7bf50a5328de843f588cb3157df8a9371f1c36cb89a9c25ee6ae837e060b091e5a82dd3ea4b808

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
